"""SYNTHESIZED auto_tuned.py — DO NOT HAND-EDIT.
Generated by scripts/synthesize_auto_tuned.py from 10-agent sweep results.

Layered onto config.py defaults via try/except import block at end of config.py.

Sources:
  SL_OVERRIDE_AUTO              ← tune_180d_pass1.json + rescue_losers_auto_dict.py
  SIGNAL_QUALITY_SYMBOL_AUTO    ← tune_180d_pass1.json + rescue overrides
  DIRECTION_BIAS_AUTO           ← direction_bias_auto_dict.py + rescue forced directions
  RISK_CAP_AUTO                 ← risk_caps_auto_dict.py + walk-forward risk halving
  TOXIC_HOURS_PER_SYMBOL_AUTO   ← toxic_hours_auto_dict.py
  TRAIL_OVERRIDE_AUTO           ← trail_overrides_auto_dict.py
"""

# Per-symbol ATR SL multiplier (merges into SYMBOL_ATR_SL_OVERRIDE)
SL_OVERRIDE_AUTO = {
    'AUDJPY'             : 2.75,
    'AUDUSD'             : 3.0,
    'BCHUSD'             : 3.5,
    'CADJPY'             : 2.0,
    'CHFJPY'             : 3.0,
    'COPPER-Cr'             : 1.75,
    'DJ30.r'             : 0.75,
    'ETHUSD'             : 4.0,
    'EURAUD'             : 3.0,
    'EURCHF'             : 3.0,
    'EURGBP'             : 4.0,
    'EURUSD'             : 2.0,
    'FRA40.r'             : 1.75,
    'GBPAUD'             : 3.0,
    'GBPCHF'             : 3.0,
    'GBPJPY'             : 1.75,
    'GBPUSD'             : 1.5,
    'GER40.r'             : 2.25,
    'HK50.r'             : 1.75,
    'NAS100.r'             : 0.75,
    'NG-Cr'             : 1.75,
    'SP500.r'             : 2.0,
    'SWI20.r'             : 2.0,
    'UK100.r'             : 1.0,
    'UKOUSD'             : 4.0,
    'US2000.r'             : 0.5,
    'USDCAD'             : 4.0,
    'USDCHF'             : 3.0,
    'USDJPY'             : 3.0,
    'XAGUSD'             : 2.75,
    'XAUUSD'             : 2.5,
}

# Per-symbol per-regime signal quality threshold (merges into SIGNAL_QUALITY_SYMBOL)
SIGNAL_QUALITY_SYMBOL_AUTO = {
    'AUDJPY'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'AUDUSD'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'BCHUSD'             : {'trending': 50, 'ranging': 50, 'volatile': 50, 'low_vol': 50},
    'CADJPY'             : {'trending': 40, 'ranging': 45, 'volatile': 40, 'low_vol': 40},
    'CHFJPY'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'COPPER-Cr'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'DJ30.r'             : {'trending': 40, 'ranging': 42, 'volatile': 40, 'low_vol': 40},
    'ETHUSD'             : {'trending': 35, 'ranging': 40, 'volatile': 35, 'low_vol': 35},
    'EURAUD'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'EURCHF'             : {'trending': 35, 'ranging': 40, 'volatile': 35, 'low_vol': 35},
    'EURGBP'             : {'trending': 50, 'ranging': 50, 'volatile': 50, 'low_vol': 50},
    'EURUSD'             : {'trending': 40, 'ranging': 45, 'volatile': 40, 'low_vol': 40},
    'FRA40.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'GBPAUD'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'GBPCHF'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'GBPJPY'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'GBPUSD'             : {'trending': 35, 'ranging': 40, 'volatile': 35, 'low_vol': 35},
    'GER40.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'HK50.r'             : {'trending': 47, 'ranging': 42, 'volatile': 47, 'low_vol': 47},
    'NAS100.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'NG-Cr'             : {'trending': 43, 'ranging': 42, 'volatile': 43, 'low_vol': 43},
    'SP500.r'             : {'trending': 40, 'ranging': 45, 'volatile': 40, 'low_vol': 40},
    'SWI20.r'             : {'trending': 45, 'ranging': 45, 'volatile': 45, 'low_vol': 45},
    'UK100.r'             : {'trending': 40, 'ranging': 45, 'volatile': 40, 'low_vol': 40},
    'UKOUSD'             : {'trending': 50, 'ranging': 50, 'volatile': 50, 'low_vol': 50},
    'US2000.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'USDCAD'             : {'trending': 35, 'ranging': 40, 'volatile': 35, 'low_vol': 35},
    'USDCHF'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'USDJPY'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'XAGUSD'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'XAUUSD'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
}

# Per-symbol direction bias LONG/SHORT/BOTH (merges into DIRECTION_BIAS)
DIRECTION_BIAS_AUTO = {
    'AUDJPY'             : 'LONG',
    'AUDUSD'             : 'LONG',
    'BCHUSD'             : 'SHORT',
    'ETHUSD'             : 'LONG',
    'EURAUD'             : 'SHORT',
    'EURCHF'             : 'LONG',
    'EURGBP'             : 'SHORT',
    'GBPAUD'             : 'SHORT',
    'GBPCHF'             : 'SHORT',
    'GBPJPY'             : 'LONG',
    'GBPUSD'             : 'LONG',
    'UKOUSD'             : 'LONG',
    'US2000.r'             : 'LONG',
    'USDCAD'             : 'LONG',
    'USDCHF'             : 'SHORT',
    'XAGUSD'             : 'LONG',
}

# Per-symbol risk-percent cap (merges into SYMBOL_RISK_CAP). Default base risk is 0.8%.
RISK_CAP_AUTO = {
    'AUDJPY'             : 0.4,
    'BCHUSD'             : 0.6,
    'ETHUSD'             : 0.5,
    'EURAUD'             : 1.2,
    'GBPCHF'             : 0.6,
    'XAGUSD'             : 1.0,
    'XAUUSD'             : 1.2,
}

# Per-symbol toxic UTC hours, added on top of TOXIC_HOURS_UTC.
TOXIC_HOURS_PER_SYMBOL_AUTO = {
    'CADJPY'             : {8},
    'COPPER-Cr'             : {15},
    'EURUSD'             : {6},
    'GBPCHF'             : {10},
    'GBPJPY'             : {6},
    'NAS100.r'             : {10},
    'SP500.r'             : {7, 8},
    'UK100.r'             : {16, 17},
    'US2000.r'             : {7},
}

# Per-symbol trail profile (replaces SYMBOL_TRAIL_OVERRIDE for these symbols).
TRAIL_OVERRIDE_AUTO = {
    'ETHUSD'             : [(10.0, 0.2, 'trail'), (5.0, 0.4, 'trail'), (2.5, 0.6, 'trail'), (1.5, 0.5, 'lock'), (0.7, 0.0, 'be')],
    'USDCAD'             : [(15.0, 0.3, 'trail'), (8.0, 0.5, 'trail'), (3.0, 0.5, 'lock'), (1.0, 0.0, 'be')],
    'XAUUSD'             : [(15.0, 0.3, 'trail'), (8.0, 0.5, 'trail'), (3.0, 0.5, 'lock'), (1.0, 0.0, 'be')],
}
