"""SYNTHESIZED auto_tuned.py — DO NOT HAND-EDIT.
Generated by scripts/synthesize_auto_tuned.py from 10-agent sweep results.

Layered onto config.py defaults via try/except import block at end of config.py.

Sources:
  SL_OVERRIDE_AUTO              ← tune_180d_pass1.json + rescue_losers_auto_dict.py
  SIGNAL_QUALITY_SYMBOL_AUTO    ← tune_180d_pass1.json + rescue overrides
  DIRECTION_BIAS_AUTO           ← direction_bias_auto_dict.py + rescue forced directions
  RISK_CAP_AUTO                 ← risk_caps_auto_dict.py + walk-forward risk halving
  TOXIC_HOURS_PER_SYMBOL_AUTO   ← toxic_hours_auto_dict.py
  TRAIL_OVERRIDE_AUTO           ← trail_overrides_auto_dict.py
"""

# Per-symbol ATR SL multiplier (merges into SYMBOL_ATR_SL_OVERRIDE)
SL_OVERRIDE_AUTO = {
    'AUDJPY'             : 2.25,
    'BTCUSD'             : 1.25,
    'CHFJPY'             : 3.0,
    'DJ30.r'             : 2.0,
    'EURUSD'             : 2.25,
    'JPN225ft'             : 2.5,
    'NAS100.r'             : 2.75,
    'SP500.r'             : 2.25,
    'SPI200.r'             : 0.75,
    'SWI20.r'             : 3.0,
    'UK100.r'             : 2.5,
    'US2000.r'             : 0.5,
    'USDCAD'             : 4.0,
    'USDJPY'             : 2.5,
    'USOUSD'             : 2.25,
    'XAUUSD'             : 0.75,
    'XPTUSD.r'             : 2.25,
}

# Per-symbol per-regime signal quality threshold (merges into SIGNAL_QUALITY_SYMBOL)
SIGNAL_QUALITY_SYMBOL_AUTO = {
    'AUDJPY'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'BTCUSD'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'CHFJPY'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'DJ30.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'EURUSD'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'JPN225ft'             : {'trending': 40, 'ranging': 45, 'volatile': 40, 'low_vol': 40},
    'NAS100.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'SP500.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'SPI200.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'SWI20.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'UK100.r'             : {'trending': 40, 'ranging': 45, 'volatile': 40, 'low_vol': 40},
    'US2000.r'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'USDCAD'             : {'trending': 35, 'ranging': 40, 'volatile': 35, 'low_vol': 35},
    'USDJPY'             : {'trending': 37, 'ranging': 45, 'volatile': 37, 'low_vol': 37},
    'USOUSD'             : {'trending': 37, 'ranging': 48, 'volatile': 37, 'low_vol': 37},
    'XAUUSD'             : {'trending': 37, 'ranging': 42, 'volatile': 37, 'low_vol': 37},
    'XPTUSD.r'             : {'trending': 37, 'ranging': 53, 'volatile': 37, 'low_vol': 37},
}

# Per-symbol direction bias LONG/SHORT/BOTH (merges into DIRECTION_BIAS)
DIRECTION_BIAS_AUTO = {
    'AUDJPY'             : 'LONG',
    'JPN225ft'             : 'LONG',
    'NAS100.r'             : 'LONG',
    'USDCAD'             : 'LONG',
    'USOUSD'             : 'SHORT',
    'XAUUSD'             : 'SHORT',
    'XPTUSD.r'             : 'LONG',
}

# Per-symbol risk-percent cap (merges into SYMBOL_RISK_CAP). Default base risk is 0.8%.
RISK_CAP_AUTO = {
    'AUDJPY'             : 0.4,
    'BTCUSD'             : 1.0,
    'XAUUSD'             : 1.2,
}

# Per-symbol toxic UTC hours, added on top of TOXIC_HOURS_UTC.
TOXIC_HOURS_PER_SYMBOL_AUTO = {
    'EURUSD'             : {6},
    'US2000.r'             : {8},
}

# Per-symbol trail profile (replaces SYMBOL_TRAIL_OVERRIDE for these symbols).
TRAIL_OVERRIDE_AUTO = {
    'BTCUSD'             : [(10.0, 'trail', 0.2), (5.0, 'trail', 0.4), (2.5, 'trail', 0.6), (1.5, 'lock', 0.5), (0.7, 'be', 0.0)],
    'JPN225ft'             : [(10.0, 'trail', 0.2), (5.0, 'trail', 0.4), (2.5, 'trail', 0.6), (1.5, 'lock', 0.5), (0.7, 'be', 0.0)],
    'XAUUSD'             : [(3.0, 'trail', 0.4), (2.5, 'lock', 1.5), (2.0, 'lock', 1.2), (1.5, 'lock', 1.0), (1.0, 'lock', 0.7), (0.7, 'lock', 0.4), (0.4, 'be', 0.0)],
}
