"""
Read tune_<days>d_<pass>.json and write auto_tuned.py with per-symbol overrides.

config.py imports auto_tuned at the bottom of its config block and merges into the
SYMBOL_ATR_SL_OVERRIDE / SIGNAL_QUALITY_SYMBOL dicts. This keeps hand-tuned values
intact while allowing the loop optimizer to layer improvements on top.

Acceptance rule for an override:
  - tuned PF >= 1.10
  - tuned PnL > baseline PnL + $5  (avoid noise-level changes)
  - tuned trades >= 20 (statistical sanity)
  - tuned DD <= 20%
"""
import sys, json, os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DAYS = int(os.environ.get("TUNE_DAYS", "180"))
PASS = os.environ.get("TUNE_PASS", "pass1")
TUNE_PATH = ROOT / "backtest" / "results" / f"tune_{DAYS}d_{PASS}.json"
OUT_PATH = ROOT / "auto_tuned.py"


def main():
    if not TUNE_PATH.exists():
        print(f"NOT FOUND: {TUNE_PATH}")
        sys.exit(1)
    data = json.load(open(TUNE_PATH))
    results = data["results"]

    sl_overrides = {}
    quality_overrides = {}
    accepted, rejected = [], []

    for sym, r in sorted(results.items()):
        base = r.get("baseline") or {}
        best = r.get("best") or {}
        if not best.get("result"):
            rejected.append((sym, "no viable best"))
            continue
        br = best["result"]
        bp = best["params"]
        bp_pnl = br["pnl"]
        base_pnl = base.get("pnl", 0)

        if br["pf"] < 1.10:
            rejected.append((sym, f"pf {br['pf']:.2f} < 1.10"))
            continue
        if br["trades"] < 20:
            rejected.append((sym, f"trades {br['trades']} < 20"))
            continue
        if br["dd"] > 20:
            rejected.append((sym, f"dd {br['dd']:.1f}% > 20%"))
            continue
        if bp_pnl <= base_pnl + 5:
            rejected.append((sym, f"pnl ${bp_pnl:.0f} not > baseline ${base_pnl:.0f}+$5"))
            continue

        sl_overrides[sym] = round(float(bp["sl_atr_mult"]), 2)
        quality_overrides[sym] = dict(bp["min_quality"])
        accepted.append((sym, br, bp, base_pnl))

    # Render auto_tuned.py
    lines = [
        '"""AUTO-GENERATED by scripts/apply_tuned_params.py — do not hand-edit.',
        f'Source: {TUNE_PATH.name}  Captured: {data.get("captured_at")}',
        f'Accepted {len(accepted)} symbols / Rejected {len(rejected)}',
        '"""',
        '',
        'SL_OVERRIDE_AUTO = {',
    ]
    for sym, _, _, _ in accepted:
        lines.append(f'    {sym!r:14s}: {sl_overrides[sym]},')
    lines += ['}', '', 'SIGNAL_QUALITY_SYMBOL_AUTO = {']
    for sym, _, _, _ in accepted:
        q = quality_overrides[sym]
        qstr = "{" + ", ".join(f'{k!r}: {v}' for k, v in q.items()) + "}"
        lines.append(f'    {sym!r:14s}: {qstr},')
    lines += ['}', '']
    OUT_PATH.write_text("\n".join(lines))

    # Summary
    total_lift = sum((br["pnl"] - base_pnl) for _, br, _, base_pnl in accepted)
    print(f"\nWrote {OUT_PATH}")
    print(f"  Accepted: {len(accepted)} symbols  total Δpnl ${total_lift:+.0f}")
    for sym, br, bp, base_pnl in accepted:
        print(f"    {sym:14s} sl={bp['sl_atr_mult']} mq=t{bp['min_quality']['trending']}/r{bp['min_quality']['ranging']}  "
              f"PnL ${base_pnl:>7.0f} → ${br['pnl']:>7.0f} ({br['pnl']-base_pnl:+.0f})  "
              f"PF {br['pf']:.2f}  n={br['trades']}")
    print(f"\n  Rejected: {len(rejected)}")
    for sym, why in rejected:
        print(f"    {sym:14s} {why}")


if __name__ == "__main__":
    main()
