#!/usr/bin/env python3 -B
"""
Profile per-symbol hour-of-day PF / WR / PnL profile across the 30 actively-tuned
symbols listed in auto_tuned.py (sourced from tune_180d_pass1.json's accepted set).

For each accepted symbol:
  1. Run a single 180d v5 backtest with current config (auto_tuned applied via config.py).
  2. Group trade `details` by entry-time UTC hour.
  3. For each hour: count, win-rate, sum PnL, avg R.

Outputs:
  - backtest/results/toxic_hours.json       : full per-symbol profile
  - backtest/results/toxic_hours_auto_dict.py: TOXIC_HOURS_PER_SYMBOL_AUTO override dict

A UTC hour is flagged "toxic" for a symbol when:
  trades >= 8 AND (sum_pnl < -25 OR avg_r < -0.3)

DOES NOT modify config.py or auto_tuned.py — read-only profiler.

Usage:
  python3 -B scripts/profile_toxic_hours.py
"""
import json
import sys
import time
from collections import defaultdict
from multiprocessing import Pool
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# Source: tune_180d_pass1.json -> apply_tuned_params.py -> auto_tuned.py (30 accepted)
from auto_tuned import SL_OVERRIDE_AUTO  # noqa: E402

ACCEPTED_SYMBOLS = sorted(SL_OVERRIDE_AUTO.keys())

DAYS = 180
WORKERS = 4

OUT_JSON = ROOT / "backtest" / "results" / "toxic_hours.json"
OUT_PY = ROOT / "backtest" / "results" / "toxic_hours_auto_dict.py"


def _run_one(symbol):
    """Worker: backtest one symbol and return (symbol, hour_profile_dict)."""
    # Defer the heavy import into the worker process to avoid pickling state.
    from backtest.v5_backtest import backtest_symbol

    t0 = time.time()
    try:
        res = backtest_symbol(symbol, days=DAYS, params=None, verbose=False)
    except Exception as e:  # noqa: BLE001
        return symbol, {"_error": f"{type(e).__name__}: {e}", "_elapsed_s": round(time.time() - t0, 1)}

    if not res or not res.get("details"):
        return symbol, {"_error": "no trades", "_elapsed_s": round(time.time() - t0, 1)}

    by_hour = defaultdict(list)
    for tr in res["details"]:
        by_hour[int(tr["hour"])].append(tr)

    profile = {}
    for h, trs in by_hour.items():
        n = len(trs)
        wins = sum(1 for t in trs if t["pnl"] > 0)
        pnl = sum(t["pnl"] for t in trs)
        avg_r = sum(t["pnl_r"] for t in trs) / n
        wr = wins / n * 100.0
        profile[h] = {
            "n": n,
            "wr": round(wr, 1),
            "pnl": round(pnl, 2),
            "avg_r": round(avg_r, 3),
        }

    profile["_meta"] = {
        "trades_total": res.get("trades", 0),
        "pf": res.get("pf", 0),
        "wr": res.get("wr", 0),
        "pnl": res.get("pnl", 0),
        "elapsed_s": round(time.time() - t0, 1),
    }
    return symbol, profile


def _build_toxic_dict(profiles, *, min_trades=8, pnl_floor=-25.0, avg_r_floor=-0.3):
    """Apply toxic-hour rule:
        trades >= min_trades AND (pnl < pnl_floor OR avg_r < avg_r_floor)
    Skip symbol if no qualifying hour."""
    toxic = {}
    for sym, prof in profiles.items():
        if not isinstance(prof, dict) or "_error" in prof:
            continue
        bad = set()
        for h, stats in prof.items():
            if not isinstance(h, int):
                continue
            if stats["n"] < min_trades:
                continue
            if stats["pnl"] < pnl_floor or stats["avg_r"] < avg_r_floor:
                bad.add(h)
        if bad:
            toxic[sym] = sorted(bad)
    return toxic


def _emit_py(toxic, path):
    lines = [
        '"""AUTO-GENERATED by scripts/profile_toxic_hours.py — do not hand-edit.',
        f"Source: 180d v5 backtest of {len(ACCEPTED_SYMBOLS)} accepted symbols.",
        "Rule: hour flagged when trades>=8 AND (pnl<-25 OR avg_r<-0.3).",
        '"""',
        "",
        "TOXIC_HOURS_PER_SYMBOL_AUTO = {",
    ]
    for sym in sorted(toxic):
        hours = ", ".join(str(h) for h in toxic[sym])
        lines.append(f"    {sym!r:<14}: {{{hours}}},")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines))


def main():
    print(f"Profiling {len(ACCEPTED_SYMBOLS)} symbols x {DAYS}d with {WORKERS} workers")
    t_start = time.time()
    with Pool(WORKERS) as pool:
        results = pool.map(_run_one, ACCEPTED_SYMBOLS)
    profiles = {sym: prof for sym, prof in results}
    elapsed = round(time.time() - t_start, 1)
    print(f"Backtests done in {elapsed}s")

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)

    # Persist raw hour profile
    serial = {
        "captured_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "days": DAYS,
        "symbols": len(ACCEPTED_SYMBOLS),
        "elapsed_s": elapsed,
        "profiles": {
            sym: {(str(k) if isinstance(k, int) else k): v for k, v in prof.items()}
            for sym, prof in profiles.items()
        },
    }
    OUT_JSON.write_text(json.dumps(serial, indent=2))
    print(f"Wrote {OUT_JSON}")

    toxic = _build_toxic_dict(profiles)
    _emit_py(toxic, OUT_PY)
    print(f"Wrote {OUT_PY}  ({len(toxic)} symbols with toxic hours)")

    # Console summary: top 3 worst hour:symbol pairs by PnL
    worst = []
    for sym, prof in profiles.items():
        if not isinstance(prof, dict) or "_error" in prof:
            continue
        for h, s in prof.items():
            if not isinstance(h, int):
                continue
            if s["n"] >= 8:
                worst.append((s["pnl"], s["avg_r"], s["n"], sym, h))
    worst.sort()
    print("\nTop 5 worst (sym, hour, n, pnl, avg_r):")
    for pnl, avg_r, n, sym, h in worst[:5]:
        print(f"  {sym:12s} h={h:02d} n={n:4d} pnl=${pnl:+8.2f} avg_r={avg_r:+.2f}")

    print("\nSymbols with toxic hours:")
    for sym in sorted(toxic):
        print(f"  {sym:12s} -> {sorted(toxic[sym])}")


if __name__ == "__main__":
    main()
