#!/usr/bin/env python3 -B
"""
Direction-bias sweep — Pass 2 of param tuning.

For each symbol in the universe, run THREE 180d backtests:
  - LONG-only   (force_direction="LONG")
  - SHORT-only  (force_direction="SHORT")
  - BOTH        (force_direction="BOTH" → bypasses any live DIR_BIAS too)

Score = pnl * pf / sqrt(max(dd, 1))   (higher is better)

Override emitted only if winner != "BOTH" AND winner_pnl > both_pnl + $50.

Outputs:
  backtest/results/direction_bias.json           — full triple-result table
  backtest/results/direction_bias_auto_dict.py   — DIRECTION_BIAS_AUTO = {...}

Run:
  python3 -B scripts/tune_direction_bias.py
"""
import sys, json, math, time
from pathlib import Path
from multiprocessing import Pool

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backtest.v5_backtest import backtest_symbol, ALL_SYMBOLS  # noqa: E402

DAYS = 180
WORKERS = 6
RESULTS_DIR = ROOT / "backtest" / "results"
JSON_OUT = RESULTS_DIR / "direction_bias.json"
DICT_OUT = RESULTS_DIR / "direction_bias_auto_dict.py"
GAIN_THRESHOLD = 50.0  # $ winner must beat BOTH by


def _score(r):
    """Composite score: pnl * pf / sqrt(max(dd, 1)). Returns 0 for empty/None."""
    if not r or r.get("trades", 0) == 0:
        return 0.0
    pnl = float(r.get("pnl", 0.0))
    pf = float(r.get("pf", 0.0))
    dd = float(r.get("dd", 0.0))
    return pnl * pf / math.sqrt(max(dd, 1.0))


def _run_one(args):
    sym, direction = args
    try:
        params = {} if direction == "BOTH" else {"force_direction": direction}
        r = backtest_symbol(sym, days=DAYS, params=params, verbose=False)
        return (sym, direction, r)
    except Exception as e:
        return (sym, direction, {"error": str(e), "trades": 0, "pnl": 0, "pf": 0, "dd": 0})


def main():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    symbols = sorted(ALL_SYMBOLS.keys())
    jobs = [(s, d) for s in symbols for d in ("LONG", "SHORT", "BOTH")]
    print(f"[dir-bias] Sweeping {len(symbols)} symbols x 3 directions = {len(jobs)} jobs "
          f"(workers={WORKERS}, days={DAYS})")

    t0 = time.time()
    with Pool(WORKERS) as pool:
        out = pool.map(_run_one, jobs)
    elapsed = time.time() - t0
    print(f"[dir-bias] Completed in {elapsed:.1f}s")

    # Group: sym -> {LONG, SHORT, BOTH}
    grouped = {s: {} for s in symbols}
    for sym, direction, r in out:
        grouped[sym][direction] = r

    table = {}
    overrides = {}  # winner != BOTH and beats BOTH by >$50
    gain_rows = []

    for sym in symbols:
        g = grouped[sym]
        long_r, short_r, both_r = g.get("LONG"), g.get("SHORT"), g.get("BOTH")
        scores = {
            "LONG":  _score(long_r),
            "SHORT": _score(short_r),
            "BOTH":  _score(both_r),
        }
        winner = max(scores, key=lambda k: scores[k])
        long_pnl  = float((long_r  or {}).get("pnl", 0.0))
        short_pnl = float((short_r or {}).get("pnl", 0.0))
        both_pnl  = float((both_r  or {}).get("pnl", 0.0))
        winner_pnl = {"LONG": long_pnl, "SHORT": short_pnl, "BOTH": both_pnl}[winner]

        table[sym] = {
            "long":   long_r,
            "short":  short_r,
            "both":   both_r,
            "winner": winner,
            "score":  round(scores[winner], 2),
            "scores": {k: round(v, 2) for k, v in scores.items()},
            "winner_pnl_vs_both": round(winner_pnl - both_pnl, 2),
        }

        if winner != "BOTH" and (winner_pnl > both_pnl + GAIN_THRESHOLD):
            overrides[sym] = winner
            gain_rows.append((sym, winner, winner_pnl - both_pnl, scores[winner], scores["BOTH"]))

    # Persist json
    with open(JSON_OUT, "w") as f:
        json.dump(table, f, indent=2, default=str)
    print(f"[dir-bias] Wrote {JSON_OUT}")

    # Persist DIRECTION_BIAS_AUTO dict file (separate, as required)
    lines = [
        '"""AUTO-GENERATED by scripts/tune_direction_bias.py — direction-bias sweep results.',
        f'Period: {DAYS}d  Symbols: {len(symbols)}  Overrides emitted: {len(overrides)}',
        f'Rule: emit override only if winner != "BOTH" and winner_pnl > both_pnl + ${GAIN_THRESHOLD:.0f}',
        '"""',
        '',
        'DIRECTION_BIAS_AUTO = {',
    ]
    for sym in sorted(overrides):
        lines.append(f'    {sym!r:14s}: {overrides[sym]!r},')
    lines += ['}', '']
    DICT_OUT.write_text("\n".join(lines))
    print(f"[dir-bias] Wrote {DICT_OUT}")

    # Console summary
    helps = len(overrides)
    print()
    print(f"  Total symbols evaluated : {len(symbols)}")
    print(f"  Direction bias helps    : {helps}")
    if gain_rows:
        gain_rows.sort(key=lambda x: x[2], reverse=True)
        print(f"  Top 5 by PnL gain over BOTH:")
        for sym, w, gain, sc_w, sc_b in gain_rows[:5]:
            print(f"    {sym:12s}  {w:5s}  gain=${gain:+8.2f}  score {sc_b:.2f} -> {sc_w:.2f}")
    else:
        print("  No symbols cleared the +$50 threshold.")

    # Detail dump for ALL symbols (helpful for synthesis)
    print()
    print("  Per-symbol triple summary (pnl @ pf @ dd):")
    for sym in symbols:
        t = table[sym]
        l, s, b = t["long"], t["short"], t["both"]
        def fmt(r):
            if not r: return "  (no trades)"
            return f"${r.get('pnl',0):>7.0f} pf{r.get('pf',0):>4.2f} dd{r.get('dd',0):>4.1f}% n{r.get('trades',0):>3d}"
        marker = "*" if sym in overrides else " "
        print(f"   {marker}{sym:12s} L:{fmt(l)} | S:{fmt(s)} | B:{fmt(b)} -> {t['winner']}")


if __name__ == "__main__":
    main()
